path_generator:
  ros__parameters:
    use_sim_time: False
    point_1: [0.5, 0.5]
    point_2: [0.0, 0.5]
    point_3: [0.25, 1.5]
    point_4: [0.0, 0.0]
    linear_vel: 0.2
    angular_vel: 0.2

controller_points:
  ros__parameters:
    use_sim_time: False
